[package]
name = "whiskers-launcher-emoji-extension"
version = "1.0.0"
edition = "2021"

[dependencies]
emoji = { git = "https://github.com/richardanaya/emoji-rs" }
#whiskers-launcher-rs = { git = "https://github.com/lighttigerXIV/whiskers-launcher-rs.git" }
whiskers-launcher-rs = { path = "/home/lighttigerxiv/Projects/Cli/whiskers-launcher-rs" }
#tokio = { version = "1.3.7", features = ["full"]}
